//! 主题目录（0.25.11 主题调试台）。
//!
//! ⚠️ 与 settings.html 的 `<select id="theme">` 手工同步维护：新增主题时两处都要加。
//! 调试台是纯静态页，不走 settings 的 config 回填，所以这里常驻一份镜像目录。

/** @type {Array<{value: string, label: string, group: string}>} */
export const THEME_CATALOG = [
    { value: "auto", label: "跟随系统", group: "Blink" },
    { value: "light", label: "浅色", group: "Blink" },
    { value: "dark", label: "深色", group: "Blink" },
    { value: "gruvbox", label: "Gruvbox Dark", group: "Blink" },
    { value: "neutral", label: "Neutral", group: "Blink" },
    { value: "nord-snow-storm", label: "Snow Storm", group: "Nord" },
    { value: "nord-polar-night", label: "Polar Night", group: "Nord" },
    { value: "nord-frost", label: "Frost", group: "Nord" },
    { value: "nord-aurora", label: "Aurora", group: "Nord" },
    { value: "catppuccin-mocha", label: "Mocha", group: "Catppuccin" },
    { value: "catppuccin-macchiato", label: "Macchiato", group: "Catppuccin" },
    { value: "catppuccin-frappe", label: "Frappé", group: "Catppuccin" },
    { value: "catppuccin-latte", label: "Latte", group: "Catppuccin" },
    { value: "genshin-kokomi", label: "心海", group: "Genshin" },
    { value: "genshin-fischl", label: "菲谢尔", group: "Genshin" },
    { value: "genshin-nilou", label: "妮露", group: "Genshin" },
    { value: "genshin-ganyu", label: "甘雨", group: "Genshin" },
    { value: "genshin-hutao", label: "胡桃", group: "Genshin" },
    { value: "genshin-diona", label: "迪奥娜", group: "Genshin" },
    { value: "genshin-nahida", label: "纳西妲", group: "Genshin" },
    { value: "genshin-ayaka", label: "神里绫华", group: "Genshin" },
    { value: "genshin-klee", label: "可莉", group: "Genshin" },
    { value: "genshin-sigewinne", label: "希格雯", group: "Genshin" },
    { value: "genshin-sucrose", label: "砂糖", group: "Genshin" },
    { value: "suzume-journey", label: "铃芽之旅", group: "Custom" },
    { value: "jay-november", label: "Jay 十一月的萧邦", group: "Custom" },
    { value: "jay-ye-huimei", label: "Jay 叶惠美", group: "Custom" },
    { value: "nvchad-aquarium", label: "NvChad Aquarium", group: "NvChad Dark" },
    { value: "nvchad-ashes", label: "NvChad Ashes", group: "NvChad Dark" },
    { value: "nvchad-bearded-arc", label: "NvChad Bearded Arc", group: "NvChad Dark" },
    { value: "nvchad-catppuccin", label: "NvChad Catppuccin", group: "NvChad Dark" },
    { value: "nvchad-chadracula-evondev", label: "NvChad Chadracula Evondev", group: "NvChad Dark" },
    { value: "nvchad-chadracula", label: "NvChad Chadracula", group: "NvChad Dark" },
    { value: "nvchad-chadtain", label: "NvChad Chadtain", group: "NvChad Dark" },
    { value: "nvchad-chocolate", label: "NvChad Chocolate", group: "NvChad Dark" },
    { value: "nvchad-dark_horizon", label: "NvChad Dark Horizon", group: "NvChad Dark" },
    { value: "nvchad-decay", label: "NvChad Decay", group: "NvChad Dark" },
    { value: "nvchad-doomchad", label: "NvChad Doomchad", group: "NvChad Dark" },
    { value: "nvchad-everblush", label: "NvChad Everblush", group: "NvChad Dark" },
    { value: "nvchad-everforest", label: "NvChad Everforest", group: "NvChad Dark" },
    { value: "nvchad-falcon", label: "NvChad Falcon", group: "NvChad Dark" },
    { value: "nvchad-flexoki", label: "NvChad Flexoki", group: "NvChad Dark" },
    { value: "nvchad-gatekeeper", label: "NvChad Gatekeeper", group: "NvChad Dark" },
    { value: "nvchad-github_dark", label: "NvChad Github Dark", group: "NvChad Dark" },
    { value: "nvchad-gruvbox", label: "NvChad Gruvbox", group: "NvChad Dark" },
    { value: "nvchad-gruvchad", label: "NvChad Gruvchad", group: "NvChad Dark" },
    { value: "nvchad-jabuti", label: "NvChad Jabuti", group: "NvChad Dark" },
    { value: "nvchad-jellybeans", label: "NvChad Jellybeans", group: "NvChad Dark" },
    { value: "nvchad-kanagawa", label: "NvChad Kanagawa", group: "NvChad Dark" },
    { value: "nvchad-material-darker", label: "NvChad Material Darker", group: "NvChad Dark" },
    { value: "nvchad-melange", label: "NvChad Melange", group: "NvChad Dark" },
    { value: "nvchad-mito-laser", label: "NvChad Mito Laser", group: "NvChad Dark" },
    { value: "nvchad-monekai", label: "NvChad Monekai", group: "NvChad Dark" },
    { value: "nvchad-monochrome", label: "NvChad Monochrome", group: "NvChad Dark" },
    { value: "nvchad-mountain", label: "NvChad Mountain", group: "NvChad Dark" },
    { value: "nvchad-nightfox", label: "NvChad Nightfox", group: "NvChad Dark" },
    { value: "nvchad-nightlamp", label: "NvChad Nightlamp", group: "NvChad Dark" },
    { value: "nvchad-nightowl", label: "NvChad Nightowl", group: "NvChad Dark" },
    { value: "nvchad-nord", label: "NvChad Nord", group: "NvChad Dark" },
    { value: "nvchad-oceanic-next", label: "NvChad Oceanic Next", group: "NvChad Dark" },
    { value: "nvchad-onedark", label: "NvChad Onedark", group: "NvChad Dark" },
    { value: "nvchad-onenord", label: "NvChad Onenord", group: "NvChad Dark" },
    { value: "nvchad-oxocarbon", label: "NvChad Oxocarbon", group: "NvChad Dark" },
    { value: "nvchad-palenight", label: "NvChad Palenight", group: "NvChad Dark" },
    { value: "nvchad-pastelDark", label: "NvChad Pasteldark", group: "NvChad Dark" },
    { value: "nvchad-pastelbeans", label: "NvChad Pastelbeans", group: "NvChad Dark" },
    { value: "nvchad-penumbra_dark", label: "NvChad Penumbra Dark", group: "NvChad Dark" },
    { value: "nvchad-poimandres", label: "NvChad Poimandres", group: "NvChad Dark" },
    { value: "nvchad-radium", label: "NvChad Radium", group: "NvChad Dark" },
    { value: "nvchad-rosepine", label: "NvChad Rosepine", group: "NvChad Dark" },
    { value: "nvchad-rxyhn", label: "NvChad Rxyhn", group: "NvChad Dark" },
    { value: "nvchad-solarized_dark", label: "NvChad Solarized Dark", group: "NvChad Dark" },
    { value: "nvchad-solarized_osaka", label: "NvChad Solarized Osaka", group: "NvChad Dark" },
    { value: "nvchad-sweetpastel", label: "NvChad Sweetpastel", group: "NvChad Dark" },
    { value: "nvchad-tokyodark", label: "NvChad Tokyodark", group: "NvChad Dark" },
    { value: "nvchad-tokyonight", label: "NvChad Tokyonight", group: "NvChad Dark" },
    { value: "nvchad-tomorrow_night", label: "NvChad Tomorrow Night", group: "NvChad Dark" },
    { value: "nvchad-tundra", label: "NvChad Tundra", group: "NvChad Dark" },
    { value: "nvchad-vscode_dark", label: "NvChad Vscode Dark", group: "NvChad Dark" },
    { value: "nvchad-wombat", label: "NvChad Wombat", group: "NvChad Dark" },
    { value: "nvchad-yoru", label: "NvChad Yoru", group: "NvChad Dark" },
    { value: "nvchad-ayu_light", label: "NvChad Ayu Light", group: "NvChad Light" },
    { value: "nvchad-blossom_light", label: "NvChad Blossom Light", group: "NvChad Light" },
    { value: "nvchad-everforest_light", label: "NvChad Everforest Light", group: "NvChad Light" },
    { value: "nvchad-flex-light", label: "NvChad Flex Light", group: "NvChad Light" },
    { value: "nvchad-flexoki-light", label: "NvChad Flexoki Light", group: "NvChad Light" },
    { value: "nvchad-github_light", label: "NvChad Github Light", group: "NvChad Light" },
    { value: "nvchad-gruvbox_light", label: "NvChad Gruvbox Light", group: "NvChad Light" },
    { value: "nvchad-material-lighter", label: "NvChad Material Lighter", group: "NvChad Light" },
    { value: "nvchad-nano-light", label: "NvChad Nano Light", group: "NvChad Light" },
    { value: "nvchad-oceanic-light", label: "NvChad Oceanic Light", group: "NvChad Light" },
    { value: "nvchad-one_light", label: "NvChad One Light", group: "NvChad Light" },
    { value: "nvchad-onenord_light", label: "NvChad Onenord Light", group: "NvChad Light" },
    { value: "nvchad-penumbra_light", label: "NvChad Penumbra Light", group: "NvChad Light" },
    { value: "nvchad-rosepine-dawn", label: "NvChad Rosepine Dawn", group: "NvChad Light" },
];
